### ISSUE TITLE
Py3 Request

### ISSUE THREAD

**Issue by PotatomanNg** [cbillingham/focus-plane#1]
Would you be able to update this for PY3? Newer versions of maya use Py3, and this tool is such a life saver

**Comment by cbillingham** [comment]
Oh yeah. I think that should be pretty fast to update. Will let you know when its updated

**Comment by cbillingham** [comment]
Okay I updated the snippet and tested in Maya 2023 with python 3. Let me know if thats working alright for you. Reformatted the code a bit as well.

**Comment by PotatomanNg** [comment]
Works great thankyou!!!
